[workspace]
members = ["packages/serde_json", "packages/serde_json_macro"]
name = "strapex_serde_json"
version = "0.1.0"
description = "Strapex Serde Json Package"
homepage = "https://github.com/StrapexLabs/serde_json"
cairo-version = "2.10.1"

[workspace.dependencies]
starknet = "2.10.1"
cairo_test = "2.10.1"

[workspace.tool.fmt]
sort-module-level-items = true

[scripts]
all = "scarb build && scarb test"
